name: CI
## triggerを決める
on:
  push:
    branches:
      - main
    paths-ignore:
     - README.md
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env: 
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
jobs:
  test:
    runs-on: macOS-latest
    env: 
    MINT_PATH: mint/lib
    MINT_LINK_PATH: mint/bin
    steps:
      - uses: actions/cache@v2
      - name : Cache Gems
      with: 
      path: vendor/bundle
      key: $${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      restore-keys:
       ${{ runner.os }} -gems-
      -name: Install Bundled Gems
      run: make install-bundler
      -- name: Install Mint
      run: brew install mint
      - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: mint
        key: ${{ runner.os }} -mint-${{ hashFiles('**/Mintfile') }}
        restore-keys:
         ${{ runner.os }}-mint-
       - name: Install Carthage frameworks
       run: make install-carthage
       - name: -Generate Xcode project and install Pods
       run: make generate-xcodeproj
       
       -name: Xcode build
       run: make build-debug
       -name: Xcode test
       run: make test
       
       
